"""
Django settings for djangoday4 project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import middleware

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fjl5pe2kmv--59h3!a6r#+a4c1^#qbds__#0f&7l0_&cz4qyy_'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    'captcha',
    'article',
    'xadmin', #xadmin
    'crispy_forms',  #xadmin
    'ckeditor',   #添加ckeditor富文本编辑器
    'ckeditor_uploader',   #ckeditor进行文件上传
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'middleware.MyMiddleware.MiddleWare1',
    # 'middleware.MyMiddleware.MiddleWare2',

]

ROOT_URLCONF = 'djangoday4.urls'

#如果用户继承了AbstractUser,修改auth_user的模型
AUTH_USER_MODEL='user.UserProfile'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  #模板中引用上传的文件，并显示
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoday4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blogs',
        'USER':'root',
        'PASSWORD':'123',
        'HOST':'127.0.0.1',
        'PROT':3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
# STATIC_ROOT=os.path.join(BASE_DIR,'static')  #生产环境

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
CKEDITOR_UPLOAD_PATH='uploads/'

#发送邮箱设置
EMAIL_HOST='smtp.163.com'
EMAIL_HOST_USER='15201184475@163.com'
EMAIL_HOST_PASSWORD='cy15201184475'
EMAIL_PORT=25   #SMTP端口
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False  #126:465 ,  QQ:465  163:454


#上线更改为
# EMAIL_PORT = 465             # 端口号
# EMAIL_USE_TLS = False         # 发送的模式
# EMAIL_USE_SSL = True        # 加密模式
# DEFAULT_FROM_EMAIL = '15201184475@163.com'

#添加一个登陆路由   结合 @login_required
LOGIN_URL='/user/login'


