# Generated by Django 2.0 on 2019-05-10 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_auto_20190510_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collect',
            field=models.ManyToManyField(related_name='article_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_auth', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
